apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: {{ include "mqtt-broker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: {{ .Values.service.port }}
      targetPort: mqtt
    - name: websocket
      port: {{ .Values.service.websocketPort }}
      targetPort: websocket