apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: whisper
  name: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: whisper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: whisper
    spec:
      containers:
        - args:
            - --model
            - base-int8
            - --language
            - en
          env:
            - name: TZ
              value: Europe/Oslo
          image: rhasspy/wyoming-whisper:latest
          name: whisper
          ports:
            - containerPort: 10300
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: whisper-claim0
      restartPolicy: Always
      volumes:
        - name: whisper-claim0
          emptyDir:
            sizeLimit: 500Mi
