apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
spec:
  replicas: 1
  strategy:
    type: Recreate

  # REQUIRED
  selector:
    matchLabels:
      app: whisper

  template:
    metadata:
      # REQUIRED â€” must match selector
      labels:
        app: whisper

    spec:
      containers:
        - args:
            - --model
            - {{ .Values.model }}
            - --language
            - en
          env:
            - name: TZ
              value: Europe/Oslo
          image: rhasspy/wyoming-whisper:latest
          name: whisper
          ports:
            - containerPort: 10300
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: whisper-claim0
      restartPolicy: Always
      volumes:
        - name: whisper-claim0
          emptyDir:
            sizeLimit: 500Mi
