image: python:alpine
args: ["-c", "apk add git; git clone https://github.com/dialgatrainer02-lab/home-lab; cd home-lab; pip install -r requirements-step.txt; ansible-galaxy install -r requirements-step.yml; ansible-playbook ./playbooks/step-ca.playbook.yml"]

# env:
  # - name: PROWLARR_API_KEY
    # valueFrom:
      # secretKeyRef:
        # name: media-stack-prowlarr
        # key: apiKey
  # - name: PROWLARR_URL
    # value: http://media-stack-prowlarr:9696/prowlarr
  # - name: SONARR_API_KEY
    # valueFrom:
      # secretKeyRef:
        # name: media-stack-sonarr
        # key: apiKey
  # - name: SONARR_URL
    # value: http://media-stack-sonarr:8989/sonarr
  # - name: RADARR_API_KEY
    # valueFrom:
      # secretKeyRef:
        # name: media-stack-radarr
        # key: apiKey
  # - name: RADARR_URL
    # value: http://media-stack-radarr:7878/radarr
# 