apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: govee2mqtt
  name: govee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: govee2mqtt
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: govee2mqtt
    spec:
      hostNetwork: true
      containers:
        - image: ghcr.io/wez/govee2mqtt:latest
          name: govee2mqtt
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: 'lanapi'
              containerPort: 4002
              protocol: UDP
              hostPort: 4002
      restartPolicy: Always
