apiVersion: apps/v1
kind: Deployment
metadata:
  name: govee2mqtt
spec:
  replicas: 1

  # REQUIRED
  selector:
    matchLabels:
      app: govee2mqtt

  template:
    metadata:
      # REQUIRED â€” must match selector
      labels:
        app: govee2mqtt
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: ghcr.io/wez/govee2mqtt:latest
          name: govee2mqtt
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: lanapi
              containerPort: 4002
              protocol: UDP
              hostPort: 4002
      restartPolicy: Always
