apiVersion: v1
kind: Secret
metadata:
  name: openbao-admin-password
  labels:
    app.kubernetes.io/name: {{ include "openbao.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc }}