apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: step-clusterissuer-writer-binding
subjects:
  - kind: ServiceAccount
    name: step-cert-manager
    namespace: certificates
roleRef:
  kind: ClusterRole
  name: step-clusterissuer-writer
  apiGroup: rbac.authorization.k8s.io
