apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: step-certificates-configmap-reader-binding
subjects:
  - kind: ServiceAccount
    name: step-certificates-reader
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: step-certificates-configmap-reader
  apiGroup: rbac.authorization.k8s.io
