apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: step-clusterissuer-reader
rules:
  - apiGroups: ["certmanager.step.sm"]
    resources:
      - stepclusterissuers
    verbs:
      - get
      - list
      - watch
