apiVersion: batch/v1
kind: Job
metadata:
  generateName: step-ca-config-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: step-certificates-reader
      containers:
        - name: config
          image: {{ .Values.image }}
          command: ["/bin/sh"]
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Never
  backoffLimit: 2
