apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certificates-configmap-reader-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: step-cert-manager
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: certificates-configmap-reader
  apiGroup: rbac.authorization.k8s.io
