apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: step-certificates-configmap-reader
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["certmanager.step.sm"]
    resources: ["stepissuers"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]