name: govee2mqtt
description: A generated Helm Chart for docker-compose from Skippbox Kompose
version: 0.0.1
apiVersion: v2
keywords:
  - docker-compose
sources:
  - https://github.com/wez/govee2mqtt/blob/main/
