name: govee2mqtt
description: govee to mqtt convert the govee lan control api to mqtt used for home assistant
version: 0.0.1
apiVersion: v2
keywords:
  - docker-compose
sources:
  - https://github.com/wez/govee2mqtt/blob/main/
