config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/Dialgatrainer02-lab/apps.git
      targetRevision: HEAD

applications:
  - name: external-dns
  # - name: certificates
  - name: openbao
