apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: piper
  name: piper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: piper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: piper
    spec:
      containers:
        - args:
            - --voice
            - en-gb-southern_english_female-low
          env:
            - name: TZ
              value: Europe/Oslo
          image: rhasspy/wyoming-piper:latest
          name: piper
          ports:
            - containerPort: 10200
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: piper-claim0
      restartPolicy: Always
      volumes:
        - name: piper-claim0
          emptyDir:
            sizeLimit: 500Mi
