apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - args:
            - --voice
            - {{ .Values.voice }}
          env:
            - name: TZ
              value: Europe/London
          image: rhasspy/wyoming-piper:latest
          name: piper
          ports:
            - containerPort: 10200
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: piper-claim0
      restartPolicy: Always
      volumes:
        - name: piper-claim0
          emptyDir:
            sizeLimit: 500Mi
