gateway:
  enabled: false
  name: example-gateway
  annotations:
    cert-manager.io/issuer: foo
  className: cilium
  listeners:
    - name: example-listener
      host: example.test.lan
      tls:
        secretName: example-tls