gateway:
  enabled: false
  name: ""
  className: ""
  listeners: []

httpRoute:
  enabled: false
  name: ""
  parentRefs: []
  hostnames: []
  rules: []


job:
  enabled: false

  generateName: media-stack-config-

  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation

  containerName: config
  image: busybox

  command:
    - /bin/sh

  args:
    - -c
    - echo "configuring media stack"

  env: []
    # - name: EXAMPLE
    #   value: "true"

  backoffLimit: 2

secrets:
  enabled: false

  items:
    - name: media-stack-config
      type: Opaque
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      stringData:
        config.yaml: |
          logLevel: info
          mediaPath: /data/media

    - name: registry-credentials
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: eyJhdXRocyI6ey4uLn19
