apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openbao-issuer
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: [{{ .Values.serviceAccountName | quote}}]
    verbs: ['create']
