apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openbao-issuer
spec:
  vault:
    path: pki_int/sign/cert-manager
    server: https://openbao.openbao.svc.cluster.local
    auth:
      kubernetes:
        role: openbao-issuer-role
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: openbao-issuer