config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/Dialgatrainer02-lab/apps.git
      targetRevision: HEAD

applications:
  # - name: blue-green
    # tool:
      # helm:
        # releaseName: blue-green
  - name: home-assistant
    namespace: home-assistant
