config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/Dialgatrainer02-lab/apps.git
      targetRevision: HEAD

applications:
  - name: home-assistant
    tool:
      helm:
        valueFiles:
          - values.yaml
